### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by drzey** [flytegg/neptune#14]
When you have an inferface in your code, neptune breaks
@Exclude does not change anything

This is the error

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because the return value of "java.lang.Class.getSuperclass()" is null
	at gg.flyte.neptune.command.CommandDispatcher.isListener(CommandDispatcher.java:207)
	at gg.flyte.neptune.command.CommandDispatcher.<init>(CommandDispatcher.java:56)
	at gg.flyte.neptune.Neptune.<init>(Neptune.java:30)
	at gg.flyte.neptune.Neptune$Builder.create(Neptune.java:77)

**Comment by drzey** [comment]
Simple fix would be just adding

if (foundClass.isInterface()) continue;

In the CommandDispacher where you loop thru classes, I've tested the solution and it works :D

**Comment by stephendotgg** [comment]
Really appreciate it
